services:
  - type: web
    name: whatsapp-cv-manager
    runtime: python
    plan: free
    branch: main
    runtimeVersion: "3.11.10"
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn cv_manager.wsgi --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_ACCESS_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADOBE_CLIENT_ID
        sync: false
      - key: ADOBE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_SHEETS_CREDENTIALS_PATH
        value: credentials.json
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
    healthCheckPath: /webhook/health/
